### ISSUE TITLE
TypeError: Cannot read property 'splice' of undefined

### ISSUE THREAD

**Issue by avalez** [jrburke/almond#99]
almond.js:413 Uncaught TypeError: Cannot read property 'splice' of undefined

Caused by some modules using define() without id and dependencies. This seems to be valid usage, according to [AMD API specification](https://github.com/amdjs/amdjs-api/blob/master/AMD.md).

Is it possible to fix this in almond?

Additional details:

I'm using [sprintf.js](https://github.com/alexei/sprintf.js) and [stacktrace.js](https://github.com/stacktracejs/stacktrace.js), and they use different syntax for define(), so it fails, e.g.:

stacktrace has:

    if (typeof define === 'function' && define.amd) {
        define(['error-stack-parser', 'stack-generator', 'stacktrace-gps'], factory);

sprintf.js has:

    if (typeof define === "function" && define.amd) {
            define(function() {

With requirejs I get this problem: http://requirejs.org/docs/errors.html#mismatch, because sprintf.js and stacktrace.js are using anonymous define.
I have also submitted issues to sprintf.js ([48](https://github.com/alexei/sprintf.js/issues/48)) and stacktrace.js ([102](https://github.com/stacktracejs/stacktrace.js/issues/102)) some time ago, with no any result.

**Comment by gustavnikolaj** [comment]
I have seen the same error in an application at work. We're fine with this not being supported, but we just want it to throw an exception. That makes it possible to debug it and more easily identify the situation.

**Comment by avalez** [comment]
I would prefer logging warning, and supporting unidentified modules.

**Comment by gustavnikolaj** [comment]
@avalez, that is outside the scope of almond. You should use require.js if that is your usecase. See the [restrictions](https://github.com/jrburke/almond/blob/37b54ea1463b9583fa0370a323907a7cefbd738f/README.md#restrictions) part of the readme.

> all modules have IDs and dependency arrays in their define() calls -- the RequireJS optimizer will take care of this for you.

**Comment by avalez** [comment]
Requirejs throws  http://requirejs.org/docs/errors.html#mismatch I would not like to use RequireJs optimizer in development, but also in production. Hopefully almond can workout anonymous id as ReqiureJS does.

**Comment by gustavnikolaj** [comment]
Almond is not meant to be used without your app being run through RequireJs Optimizer first. It's something that can replace RequireJs once that it is built and you can make more assumptions about the code. If you need this, you should not be using almond in the first place, but stick with RequireJs.

**Comment by jrburke** [comment]
@gustavnikolaj is correct, almond is only for use with built code, and for that built code to work all the define() calls need IDs. requirejs can work with anonymous modules if there is only one anon module per file and if that file is dynamically loaded. Since almond does not support dynamic loading, that is not possible in almond.

As for a better error, in the interests of keeping the code small, it would just be a throw of an Error but would not really tell what module triggered it, where that define() came from, so I am not so sure it is worth adding to the size of almond for it.

However, I am open to discussing an error that makes sense, maybe it just points to an almond wiki explaining the issue. Just want to be sensitive to how much space that takes up in almond vs its benefit, and we should have that discussion on a separate ticket from this one.
